### ISSUE TITLE
Ebola and Zika virus funding source figures

### ISSUE THREAD

**Issue by Fironet** [No-Agenda/Link-Analysis#1]
(Usually wouldn't use the issues tab for such questions but didn't see a separate contact)

Was just wondering if the figures in the 'Ebola and Zika virus funding' infographic are accurate or whether they were used as quasi-lorem ipsum for the purposes of the repo. If they are accurate would you happen to have links to the sources? Would be grateful, as I had tried tracking down some from the 'Where did it go' section but had trouble finding results.

**Comment by reelsense** [comment]
_"These data points contain typos and are only as accurate as the data reported on the No Agenda show. Your help is required finding and reporting/correcting errors and inaccuracies."_ 

Here is a clip they played from the episode this is sourced from: [849.nashownotes.com - zikafundingredux.mp3](http://adam.curry.com/enc/1470600383.838_zikafundingredux.mp3)

Here is the _"United Nations Special Envoy on Ebola"_ [PDF source](http://adam.curry.com/enc/1470600383.838_zikafundingdocument.pdf) that Curry used.

Thank you for your courage.

**Comment by Fironet** [comment]
Excellent, just what I was after. Thanks.
